apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
  labels:
    app: employee-api

spec:
  replicas: 3

  selector:
    matchLabels:
      app: employee-api

  template:
    metadata:
      labels:
        app: employee-api

    spec:
      containers:
        - name: employee-api
          image: gost0proxy/employee-management-api:1.4

          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: employee-api-config
                  key: APP_ENV
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: employee-api-secret
                  key: API_KEY
          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
